config/routes.rb
Rails.application.routes.draw do
  resources :pimps do
    resource :like, module: :pimps
  end

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }


  root 'pages#index'

end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :pimp
end

app/models/pimp.rb
class Pimp < ActiveRecord::Base
	attachment :image
	belongs_to :user
	validates :image, presence: true
	has_many :likes, dependent: :destroy
	validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :pimps, dependent: :destroy

  has_many :likes, dependent: :destroy

  def likes?(pimp)
  	# Return true or false
  	pimp.likes.where(user_id: id).any?
  end

  # Get avatar image from gravatar
  def avatar_url
  	hash = Digest::MD5.hexdigest(email)
  	"http://www.gravatar.com/avatar/#{hash}"
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name   # assuming the user model has a name
      user.name = "Your-name" if user.name.blank?
      user.email = auth.info.email
      user.email = "change-me@mail.com" if user.email.blank?
      user.password = Devise.friendly_token[0,20]
      #user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
    	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
      # Allow edit without password + registraitions controller
    	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password)}
    end

  # require 'ostruct'

  # helper_method :current_user

  # def current_user
  # 	@current_user ||= User.find session[:user_id] if session[:user_id]
  # 	if @current_user
  # 		@current_user
  # 	else
  # 		OpenStruct.new(name: 'Guest')
  # 	end
  # end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
		@pimps = Pimp.order("created_at desc").limit(9)
	end

end

app/controllers/pimps/likes_controller.rb
class Pimps::LikesController < ApplicationController

	before_action :authenticate_user!
	before_action :set_pimp

	def create
		@pimp.likes.where(user_id: current_user.id).first_or_create

		respond_to do |format|
			format.html { redirect_to @pimp }
			format.js
		end
	end

	def destroy
		@pimp.likes.where(user_id: current_user.id).destroy_all

		respond_to do |format|
			format.html { redirect_to @pimp }
			format.js
		end
	end

	private

		def set_pimp
			@pimp = Pimp.find(params[:pimp_id])
		end
end

app/controllers/pimps_controller.rb
class PimpsController < ApplicationController
  before_action :set_pimp, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index]

  # GET /pimps
  # GET /pimps.json
  def index
    @pimps = Pimp.order("created_at desc")
  end

  # GET /pimps/1
  # GET /pimps/1.json
  def show
  end

  # GET /pimps/new
  def new
    @pimp = current_user.pimps.new
  end

  # GET /pimps/1/edit
  def edit
  end

  # POST /pimps
  # POST /pimps.json
  def create
    @pimp = current_user.pimps.new(pimp_params)

    respond_to do |format|
      if @pimp.save
        format.html { redirect_to pimps_url, notice: 'Pimp was successfully created.' }
        format.json { render :show, status: :created, location: @pimp }
      else
        format.html { render :new }
        format.json { render json: @pimp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pimps/1
  # PATCH/PUT /pimps/1.json
  def update
    respond_to do |format|
      if @pimp.update(pimp_params)
        format.html { redirect_to pimps_url, notice: 'Pimp was successfully updated.' }
        format.json { render :show, status: :ok, location: @pimp }
      else
        format.html { render :edit }
        format.json { render json: @pimp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pimps/1
  # DELETE /pimps/1.json
  def destroy
    @pimp.destroy
    respond_to do |format|
      format.html { redirect_to pimps_url, notice: 'Pimp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pimp
      @pimp = Pimp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pimp_params
      params.require(:pimp).permit(:user, :name, :image)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	protected

	  def update_resource(resource, params)
	    # resource.update_without_password(params.except(:current_password))
	    resource.update_without_password(params)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pimps_helper.rb
module PimpsHelper
end

app/views/layouts/_footer.html.erb
<footer class="page-footer teal lighten-3">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Pimptalife project</h5>
        <p class="grey-text text-lighten-4">That was my first project realized with Ruby on Rails. I recently improved my front-end skills with the awesome framework : <%= link_to 'Materialize', 'http://materializecss.com/' %></p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="https://github.com/Goldenson/pimptalife"><i class="small fa fa-github"></i> Github</a></li>
          <li><a class="grey-text text-lighten-3" href="https://onemonth.com"><i class="small fa fa-medium"></i> One Month Rails</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2015 All rights reserved
    <a class="grey-text text-lighten-4 right" href="http://www.maximeorefice.me/">Maxime Orefice</a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- <div class="navbar-fixed"> -->
	<nav class="teal lighten-3">
		<div class="nav-wrapper container">
		  <%= link_to 'Pimptalife', root_path, class: 'brand-logo' %>
		  <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
		  <ul class="right hide-on-med-and-down">
		  	<% if user_signed_in? %>
			  	<li><%= link_to current_user.name, edit_user_registration_path %></li>
			    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
			    <li><%= link_to 'MyPimps', pimps_path %></li>
		  	<% else %>
		  		<li><%= link_to user_omniauth_authorize_path(:facebook) do %>
		  		<i class="fa fa-facebook-square left"></i>Login<% end %>
		  		</li>		    
		  		<li><%= link_to 'Sign Up', new_user_registration_path %></li>
			    <li><%= link_to 'Login', new_user_session_path %></li>
		  	<% end %>
		  </ul>
		  <ul class="side-nav" id="mobile-demo">
		  	<% if user_signed_in? %>
			  	<li><%= link_to current_user.name, edit_user_registration_path %></li>
			    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
			    <li><%= link_to 'MyPimps', pimps_path %></li>
		  	<% else %>
		  		<li><%= link_to 'Sign Up', new_user_registration_path %></li>
			    <li><%= link_to 'Login', new_user_session_path %></li>
		  		<li><%= link_to user_omniauth_authorize_path(:facebook) do %>
		  		<i class="fa fa-facebook-square left"></i>Login<% end %>
		  		</li>
		  	<% end %>
		  </ul>
		</div>
	</nav>
<!-- </div> -->

<script type="text/javascript">
	$(document).ready(function () {
		 $(".button-collapse").sideNav();
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pimptalife</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body class="blue-grey lighten-5">

<%= render partial: 'layouts/header' %>

<div class="container">
	<% if notice %><div class="card-panel green center-align"><%= notice %></div><% end %>
	<% if alert %><div class="card-panel red center-align"><%= alert %></div><% end %>
</div>

<%= yield %>

<%= render partial: 'layouts/footer' %>

</body>
</html>

app/views/pages/index.html.erb
<div class="parallax-container">
  <div class="parallax">
    <%= image_tag('man.jpg', class: "responsive-img") %>
  </div>
</div>

<div class="container">
	<div class="row">
      <div class="col s12">
        <div class="card-panel z-depth-2 m-t-40">
          <span class="flow-text">
            <p>Share your Pimps with everyone !
              <%= link_to new_pimp_path, class: 'waves-effect waves-teal btn-flat right' do %>
                Let's go <i class="mdi-content-send right"></i>
              <% end %>
            </p>
          </span>
        </div>
      </div>
      <div class="col s12">
        <h1 class="center-align"><b>Latest Pimps updated</b></h1>
        <div class="row">
          <% @pimps.each do |pimp| %>
          <div class="col s12 m6 l4">
            <div class="card z-depth-4">
              <div class="card-image waves-effect waves-block waves-light">
                <%= link_to pimp do %>
                  <%= attachment_image_tag(pimp, :image, :fill, 300, 200) %>
                <% end %>
              </div>
              <div class="card-content">
                <span class="card-title grey-text text-darken-4"><%= truncate(pimp.name, :length => 11) %><i class="right" id="pimp_<%= pimp.id %>_likes"><%= render partial: "pimps/likes", locals: {pimp: pimp}%></i></span>
                <!-- <span class="card-title grey-text text-darken-4"><i class="fa fa-heart-o right"> 3</i></span> -->
                <p><i class="mdi-image-timer-auto"></i><%= pimp.user.name %></p>
                  <p><small><i class="mdi-device-access-time m-r-10"></i><%= local_time_ago(pimp.created_at) %><% if current_user == pimp.user %><%= link_to 'Destroy', pimp, method: :delete, data: { confirm: 'Are you sure?' }, class: 'right' %><% end %></small></p>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
      $('.parallax').parallax();
    });
</script>

app/views/pimps/_form.html.erb
<%= form_for(@pimp) do |f| %>
  <% if @pimp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pimp.errors.count, "error") %> prohibited this pimp from being saved:</h2>

      <ul>
      <% @pimp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="input-field col s12 m6 offset-m3">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12 m6 offset-m3">
      <%= f.label :image %>
      <%= f.attachment_field :image, direct: true, presigned: true %>
    </div>
  </div>
  <div class="row">
  <!-- <div class="field"> -->
    <div class="input-field col s12 m6 offset-m3">
      <%= f.button "Pimp", class: "waves-effect waves-light btn col s12", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Pimping..."} %>
    </div>
  </div>
<% end %>

<!--  Not working yet <form action="#">
    <div class="file-field input-field">
      <input class="file-path validate" type="text"/>
      <div class="btn">
        <span>File</span>
        <input type="file" />
      </div>
    </div>
  </form> -->

app/views/pimps/_likes.html.erb
<% if user_signed_in? && current_user.likes?(pimp)%>	
	<%= link_to pimp_like_path(pimp), method: :delete, remote: true  do %>
		<i class="fa fa-heart"></i> <%= pimp.likes.count %>
	<% end %>
<% else %>
	<%= link_to pimp_like_path(pimp), method: :post, remote: true  do %>
		<i class="fa fa-heart-o"></i> <%= pimp.likes.count if pimp.likes.count > 0 %>
	<% end %>
<% end %>

<!-- < pimp.likes.each do |like| %>
	<= image_tag like.user.avatar_url, width: 20 %>
< end %> -->

app/views/pimps/edit.html.erb
<div class="container center-align">
	<div class="row">
		<div class="col s12">
			<h1>Editing Pimp</h1>
			<%= render 'form' %>
			<%= link_to 'Back', pimps_path %>
	  	</div>
	</div>
</div>

app/views/pimps/index.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <h1>Listing Pimps</h1>
      <p><%= link_to new_pimp_path, class: 'btn-floating btn-large waves-effect waves-light red right' do %>
            <i class="mdi-content-add"></i>
          <% end %>
      </p>
      <table id="responsive-table" class="bordered">
        <thead>
          <tr>
            <th>Image</th>
            <th>User</th>
            <th>Name</th>
            <th>Like</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @pimps.each do |pimp| %>
            <tr>
              <% if current_user == pimp.user %>
                <td><%= image_tag(attachment_url(pimp, :image, :fill, 500, 500), class: 'responsive-img materialboxed', size: '150') %></td>
                <td><%= pimp.user.name %></td>
                <td><%= pimp.name %></td>
                <td id="pimp_<%= pimp.id %>_likes"><%= render partial: "likes", locals: {pimp: pimp} %></td>
                <td><%= link_to 'Edit', edit_pimp_path(pimp) %></td>
                <td><%= link_to 'Destroy', pimp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('.materialboxed').materialbox();
  });
</script>

app/views/pimps/likes/create.js.erb
// =j escape the javascript response, you can put on the string safely
$("#pimp_<%= @pimp.id %>_likes").html("<%=j render partial: "pimps/likes", locals: {pimp: @pimp} %>")

app/views/pimps/likes/destroy.js.erb
// =j escape the javascript response, you can put on the string safely
$("#pimp_<%= @pimp.id %>_likes").html("<%=j render partial: "pimps/likes", locals: {pimp: @pimp} %>")

app/views/pimps/new.html.erb
<div class="container center-align">
	<div class="row">
		<div class="col s12">
			<h1>New Pimp</h1>
			<%= render 'form' %>
			<%= link_to 'Back', pimps_path %>
	  	</div>
	</div>
</div>

app/views/pimps/show.html.erb
<div class="container center-align">
	<div class="row">
		<div class="col s12">
			<p>
			  <strong><%= @pimp.name %></strong>
			</p>

			<p>
			  <%= image_tag(attachment_url(@pimp, :image, :fill, 500, 500), class: 'responsive-img') %>
			</p>
            <% if current_user == @pimp.user %>
				<%= link_to 'Edit', edit_pimp_path(@pimp) %> |
			<% end %>
			<%= link_to 'Back', pimps_path %>
			<div id="pimp_<%= @pimp.id %>_likes">
				<%= render partial: "likes", locals: {pimp: @pimp} %>
			</div>
		</div>
	</div>
</div>